apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.43.2
    helm:
      releaseName: argo-rollouts
      values: |
        controller:
          replicas: 1
          nodeSelector:
            role: system
        dashboard:
          enabled: true
          replicas: 1
          nodeSelector:
            role: system
        providerRBAC:
          providers:
            gatewayAPI: true
            awsLoadBalancerController: true
