apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  sources:
    - repoURL: https://github.com/test-task-2/gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/test-task-2/gitops.git
      targetRevision: HEAD
      path: crossplane-platform
      helm:
        valueFiles:
          - $values/terraform-values.yaml
