apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.10.0
      helm:
        releaseName: external-secrets
        values: |
          installCRDs: true
          replicaCount: 1
          global:
            nodeSelector:
              role: system
          nodeSelector:
            role: system
          serviceAccount:
            create: true
            name: external-secrets
          webhook:
            nodeSelector:
              role: system
          certController:
            nodeSelector:
              role: system
    - repoURL: https://github.com/test-task-2/gitops.git
      targetRevision: HEAD
      path: external-secrets
