"databaseSecurityGroupId": "sg-000514bc235b5c22d"
"databaseSubnets":
- "availabilityZone": "us-east-1a"
  "id": "subnet-05ee3a8b3ebfac782"
  "name": "cool-db-us-east-1a"
- "availabilityZone": "us-east-1b"
  "id": "subnet-06e2bebf2a19832da"
  "name": "cool-db-us-east-1b"
"elasticacheSecurityGroupId": "sg-027bf103a62da5898"
"elasticacheSubnets":
- "availabilityZone": "us-east-1a"
  "id": "subnet-063abdaaeae2868b2"
  "name": "cool-redis-us-east-1a"
- "availabilityZone": "us-east-1b"
  "id": "subnet-02d5a181d517d6a19"
  "name": "cool-redis-us-east-1b"
"region": "us-east-1"
"vpcId": "vpc-0dea332ec5d357a5e"
