apiVersion: gateway.k8s.aws/v1
kind: TargetGroupConfiguration
metadata:
  name: argocd-server
  namespace: argocd
spec:
  targetReference:
    group: ""
    kind: Service
    name: argocd-server
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /healthz
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: alb
      namespace: kube-system
      sectionName: https
  hostnames:
    - argocd.test-task.drunk.guru
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: argocd-server
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
