apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: app
spec:
  role: cool-karpenter-node
  amiSelectorTerms:
    - alias: al2023@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: cool
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: cool
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
    httpPutResponseHopLimit: 2
