apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: app
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  limits:
    cpu: "4"
    memory: 4Gi
  template:
    metadata:
      labels:
        role: app
        node-role.kubernetes.io/app: "true"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: app
      taints:
        - key: role
          value: app
          effect: NoSchedule
      expireAfter: 720h
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t4g.small", "t4g.micro"]
