{{- $region := required "region from terraform-values.yaml" .Values.region }}
apiVersion: rds.aws.m.upbound.io/v1beta1
kind: ParameterGroup
metadata:
  name: voting-postgres16
  namespace: {{ .Release.Namespace }}
spec:
  forProvider:
    region: {{ $region }}
    family: postgres16
    description: Voting app Postgres
    parameter:
      - name: rds.force_ssl
        value: "0"
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
---
apiVersion: rds.aws.m.upbound.io/v1beta1
kind: Instance
metadata:
  name: voting-postgres
  namespace: {{ .Release.Namespace }}
  annotations:
    crossplane.io/external-name: voting-postgres
spec:
  forProvider:
    region: {{ $region }}
    identifier: voting-postgres
    engine: postgres
    engineVersion: "16.13"
    instanceClass: db.t3.micro
    allocatedStorage: 20
    storageType: gp2
    storageEncrypted: true
    dbName: app
    username: appadmin
    passwordSecretRef:
      name: voting-app-postgres
      key: password
    dbSubnetGroupNameRef:
      name: voting-postgres
    parameterGroupNameRef:
      name: voting-postgres16
    vpcSecurityGroupIdRefs:
      - name: cool-db
    publiclyAccessible: false
    backupRetentionPeriod: 0
    skipFinalSnapshot: true
    deletionProtection: false
    autoMinorVersionUpgrade: true
    applyImmediately: true
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
