{{- $region := required "region from terraform-values.yaml" .Values.region }}
{{- range .Values.databaseSubnets }}
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    crossplane.io/external-name: {{ .id | quote }}
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: {{ $region }}
    availabilityZone: {{ .availabilityZone }}
    tags:
      Name: {{ .name }}
      Tier: db
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
{{- end }}
{{- range .Values.elasticacheSubnets }}
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{ .name }}
  namespace: crossplane-system
  annotations:
    crossplane.io/external-name: {{ .id | quote }}
spec:
  managementPolicies: ["Observe"]
  forProvider:
    region: {{ $region }}
    availabilityZone: {{ .availabilityZone }}
    tags:
      Name: {{ .name }}
      Tier: redis
  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
{{- end }}
