apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-aws
spec:
  package: xpkg.upbound.io/upbound/provider-family-aws:v2.7.2
  runtimeConfigRef:
    name: pod-identity
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-ec2
spec:
  package: xpkg.upbound.io/upbound/provider-aws-ec2:v2.7.2
  runtimeConfigRef:
    name: pod-identity
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-rds
spec:
  package: xpkg.upbound.io/upbound/provider-aws-rds:v2.7.2
  runtimeConfigRef:
    name: pod-identity
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-secretsmanager
spec:
  package: xpkg.upbound.io/upbound/provider-aws-secretsmanager:v2.7.2
  runtimeConfigRef:
    name: pod-identity
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudformation
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudformation:v2.7.2
  runtimeConfigRef:
    name: pod-identity
---
apiVersion: aws.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: PodIdentity
